remote_theme: "mmistakes/minimal-mistakes"

title: "Site personnel"
description: "Master Ingénierie des Risques Économiques et Financiers, spécialité Economic Risks and Data Sciences"

# Menu de navigation
nav:
  - title: "Accueil"
    url: index.md
  - title: "À propos de ma formation"
    url: matieres.md
  - title: "Projets"
    url: projets.md
  - title: "À propos de moi"
    url: cv.md
