theme: jekyll-theme-cayman

title: "Siham Hammouch Boudjoudi"
description: "Je suis spécialisée en data science et économétrie (Master 2), avec une solide maîtrise de Python, R et de la modélisation prédictive. Je recherche un stage de fin d’études de 6 mois, dès février/mars 2026."
